`timescale 1ns/1ps

module tb_cpe_direct_fft;

    // Parameters
    parameter DATA_WIDTH = 16;
    parameter MAX_SUBCARRIER = 128;
    parameter IDX_WIDTH = 7;

    // Clock & Reset
    reg clk;
    reg rst;

    // File I/O Variables
    integer infile, outfile, status;
    integer read_ctr;
    reg [15:0] read_i, read_q;

    // Top-Level Inputs
    reg valid_in;
    reg [IDX_WIDTH-1:0] idx;
    reg signed [DATA_WIDTH-1:0] fft_i, fft_q;
    reg is_pilot_flag;
    reg is_data_flag;

    // ---------------------------------------------------
    // Common Phase Error (CPE) Top Module
    // ---------------------------------------------------
    wire cpe_valid_out, cpe_is_data;
    wire signed [DATA_WIDTH-1:0] cpe_out_i, cpe_out_q;

    cpe_top #(
        .DATA_WIDTH(DATA_WIDTH),
        .N_FFT(MAX_SUBCARRIER)
    ) u_cpe (
        .clk(clk), .rst(rst),
        .valid_in(valid_in),
        .is_pilot_in(is_pilot_flag),
        .is_data_in(is_data_flag),
        .eq_in_i(fft_i), .eq_in_q(fft_q),
        .valid_out(cpe_valid_out),
        .is_data_out(cpe_is_data),
        .eq_out_i(cpe_out_i), .eq_out_q(cpe_out_q)
    );

    // ---------------------------------------------------
    // Phase Monitor (Triggered per Data Packet)
    // ---------------------------------------------------
    integer packet_count = 0;
    real phase_in_degrees;
    
    always @(posedge clk) begin
        // Taps into the internal wires 'phase_valid' and 'calculated_phase' 
        // generated by cpe_angle_calc within cpe_top
        if (u_cpe.phase_valid) begin 
            // Convert Q3.13 format to real degrees (Pi = 25736 in Q3.13)
            phase_in_degrees = ($signed(u_cpe.calculated_phase)) / 8192;
            
            $display("==================================================");
            $display("Packet Index  : %0d", packet_count);
            $display("Raw Phase     : %0d (Q3.13)", $signed(u_cpe.calculated_phase));
            $display("Approx Degrees: %f rad", phase_in_degrees);
            $display("==================================================");
            
            packet_count = packet_count + 1;
        end
    end

    // ---------------------------------------------------
    // Simulation Control & File I/O
    // ---------------------------------------------------
    always #5 clk = ~clk;

    initial begin
        clk = 0; rst = 0; valid_in = 0;
        is_pilot_flag = 0; is_data_flag = 0;

        infile = $fopen("../fft_output_log.txt", "r");
        outfile = $fopen("../cpe_corrected_log.txt", "w");
        
        #20 rst = 1;

        while (!$feof(infile)) begin
            @(posedge clk);
            status = $fscanf(infile, "ctr : %d | I: %h | Q: %h\n", read_ctr, read_i, read_q);
            
            if (status == 3) begin
                valid_in <= 1'b1;
                idx      <= read_ctr % MAX_SUBCARRIER;
                fft_i    <= read_i;
                fft_q    <= read_q;
                
                // Dynamically generate flags since Equalizer is bypassed
                is_pilot_flag <= (idx == 12) || (idx == 24) || (idx == 36) || (idx == 48) || 
                                 (idx == 60) || (idx == 68) || (idx == 80) || (idx == 92) || (idx == 104);
                                 
                is_data_flag  <= !((idx == 12) || (idx == 24) || (idx == 36) || (idx == 48) || 
                                   (idx == 60) || (idx == 68) || (idx == 80) || (idx == 92) || (idx == 104)) &&
                                 !((idx == 0) || (idx >= 1 && idx <= 5) || (idx >= 123 && idx <= 127));
            end else begin
                valid_in <= 1'b0;
            end
        end
        valid_in <= 1'b0;

        // Wait for CPE pipeline depth (144+ cycles)
        #2000;
        $fclose(infile);
        $fclose(outfile);
        $finish;
    end

    // Write rotated output directly to file (No BPSK module)
    always @(posedge clk) begin
        if (cpe_valid_out && cpe_is_data) begin
            $fwrite(outfile, "%h %h\n", cpe_out_i, cpe_out_q);
        end
    end

endmodule